### ISSUE TITLE
shard.yml or project.yml ?

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/shards#23]
- Shard is a sweet name, but doesn't mean anything by itself.
- Project is more to the point, but kind of boring.

**Comment by asterite** [comment]
I personally started to like `shard.yml` because the community likes it and because it can be the one file that immediately tells you that a Crystal project is there. It's also shorter than "dependency" or "library" so when speaking it's easier to say "I need a shard" than "I need a library/dependency". All of these are minor details, but my vote goes to `shard.yml` :+1:

**Comment by jhass** [comment]
+1, shard.yml

**Comment by ysbaddaden** [comment]
Let's stick to `shard.yml` then!
