### ISSUE TITLE
Why the files is inside of my project?

### ISSUE THREAD

**Issue by xdougx** [ysbaddaden/shards#68]
Why the dependencies need to be inside my project?
For all crystal projects using shards, is really needed to do this?
Is that possible to build some kind of general libs and use this lib on my project just configuring my dependency?

**Comment by asterite** [comment]
Having a global directory for this is bad. It becomes polluted, specially when you remove a depednency from your project. Having it in your project directory means it's super easy to jump into a library's code. And once you delete a project, all its dependencies are automatically removed.

**Comment by ysbaddaden** [comment]
Yes, they have to be installed this way, because they are required build dependencies for your project. Shards is merely a convenience to have them installed automatically in a repeatable way across computers.

**Comment by xdougx** [comment]
Just asking, because when you work with ruby, its common to use the rubygems, and all gems is stores in a folder depending the env (rbenv, rvm or apt-get), and when you use in another project you dont need to download then all when you start a new project.

**Comment by ysbaddaden** [comment]
We didn't go this way for Crystal. Ruby distributes applications and libraries (required at runtime) and decided to have a central place to install them. I suppose this is mostly because it distributes applications. This creates some complexity that Crystal doesn't need: we don't distribute applications, and dependencies are only required at compile time.

This allows to limit the paths where to look for when we `require "dep/file"` to the `crystal/src/dep/file.cr` (core/stdlib) or `./libs/dep/file.cr` (local), instead of having to search into all dependency folders.

A undocumented feature is to specify the `SHARDS_CACHE` environment variable in order to share a single cache folder, instead of cloning all dependencies in the local `.shards` folder. The dependencies would still be installed locally into the `libs` folder, but multiple projects can share the same repository clones. This isn't documented because we don't really support this (yet?), and if different dependencies share the same name... Shards will erase and clone the dependency again and again.

**Comment by xdougx** [comment]
understood the differences, that's fine to use in this way, also is really easy to delete or edit if needed to be done.

Thanks
