### ISSUE TITLE
Usage and binaries

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/shards#7]
Would it work like gem, in that you have both Ruby and Gem executables which both have different usage, or, will this eventually be integrated back the the compiler ? like how deps are now ?

**Comment by ysbaddaden** [comment]
I'm not sure I got the question right, but:

Rubygems distributes either end-user applications or libraries that help build end-user applications, or are required by these applications to run. Shards aims to install libraries that help build such applications, by resolving dependencies as best as it can, but nothing more. These applications will then have to be distributed by other means: system packages, homebrew, plain ZIP files, ...

Shards may eventually have hooks to run commands at given stages (eg: `postinstall`), like checking if required shared/static libraries are installed, or making a shared/static C/C++/Rust library.

Note: there is no way to create shared/static libraries with Crystal, because there is no easy way to generate functions that can be called from an outer context; it depends on a garbage collector; and many more reasons.

**Comment by bararchy** [comment]
@ysbaddaden I'll rephrase.

I'm talking about the actual shards program, will it have a different executable then crystal ? or will it be a part of the compiler ? 

As in, would I do this: shards install deps.... crystal build ...
or this: crystal shards ... crystal build ...

I hope this is a little bit more clear, sorry about the bad English :(

**Comment by asterite** [comment]
I'd eventually like to incorporate this functionality in the `crystal` binary, so you can do `crystal shards install`, etc. If that's fine with @ysbaddaden, of course :-)

**Comment by bararchy** [comment]
That would be cool, much better then two different files.

**Comment by ysbaddaden** [comment]
Dependency managers are usually distinct: ruby/gem, elixir/mix, rust/cargo, haxe/haxelib, ... so they can be developed at their own pace or replaced. I'm not sure we have to integrate it into the crystal binary, but maybe distribute it with crystal.

**Comment by asterite** [comment]
@ysbaddaden However, it's `go get`. I think having a single entry point to all of a language's functionality makes things easier for the user.

**Comment by tomas** [comment]
+1 to having a single point of entry.

**Comment by jbye** [comment]
Although I like the idea of a single point of entry, I would only give this suggestion a +1 if it is done in such a way that shards can be developed at its own pace like @ysbaddaden brings up in his comment above. 

I guess this would work in such a way that "crystal shards" would in essence just be an alias to the shards binary that is either distributed with crystal itself, or downloaded on-demand if it is missing?

**Comment by bararchy** [comment]
well, shards can be developed independently as a git (dev) version, while once every major\stable version it would be pulled into crystal

**Comment by asterite** [comment]
I acutally wouldn't mind (at all!) giving @ysbaddaden push rights for managing the dependency manager once we decide to integrate it.

**Comment by ysbaddaden** [comment]
Answered: Shards will become Crystal's package manager :bowtie:
